"""Paths for runtime files generated by ida_patch_pro."""

import os

from ..constants import HISTORY_FILENAME, SETTINGS_FILENAME, TEST_LOG_FILENAME


def _runtime_base_dir():
    """Return the directory that stores plugin runtime files."""
    try:
        return os.path.dirname(os.path.abspath(__file__))
    except Exception:
        return os.getcwd()


def _package_runtime_dir():
    """Return the package root where runtime JSON/log files are stored."""
    return os.path.dirname(_runtime_base_dir())


def runtime_file_path(filename):
    """Return a runtime file path next to the plugin package."""
    return os.path.join(_package_runtime_dir(), filename)


def test_log_path():
    """Return the test log path."""
    return runtime_file_path(TEST_LOG_FILENAME)


def history_file_path():
    """Return the history JSON path."""
    return runtime_file_path(HISTORY_FILENAME)


def settings_file_path():
    """Return the settings JSON path."""
    return runtime_file_path(SETTINGS_FILENAME)
